Repository textileio/powergate, pull requests merged in 2020-10, with the labels that each got.

#633 FFS scheduler improvements and knobs
  .gitignore
  api/client/ffs.go
  api/client/utils_test.go
  api/server/server.go
  cmd/powd/main.go
  deals/module/deals.go
  deals/module/deals_test.go
  ffs/api/api_jobs.go
  ffs/filcold/filcold.go
  ffs/integrationtest/integrationtest.go
  ffs/integrationtest/logger/logger_test.go
  ffs/interfaces.go
  ffs/joblogger/joblogger.go
  ffs/manager/manager.go
  ffs/manager/manager_test.go
  ffs/minerselector/sr2/sr2.go
  ffs/rpc/rpc.go
  ffs/rpc/rpc.pb.go
  ffs/rpc/rpc.proto
  ffs/scheduler/internal/sjstore/sjstore.go
  ffs/scheduler/scheduler.go
  ffs/scheduler/scheduler_storage.go
  ffs/types.go
  go.mod
  go.sum
  index/ask/runner/runner.go
Labels: enhancement, patch

#645 Found some Client fixes
  api/client/ffs.go
  cli-docs/pow/pow_ffs_config_set-default.md
  cli-docs/pow/pow_ffs_show.md
  cmd/pow/cmd/ffs_config_set_default.go
  cmd/pow/cmd/ffs_show.go
Labels: bugfix, patch

#644 Support Lotus v0.8.1
  docker/docker-compose-localnet.yaml
  ffs/minerselector/sr2/sr2.go
  go.mod
  go.sum
  index/ask/runner/runner.go
  tests/ldevnet.go
Labels: enhancement, minor

#646 Update go-ipfs to 0.7.0
  docker/ipfs-image.yaml
  tests/docker.go
Labels: enhancement, patch

#660 Trackstore fixes & more logging
  api/server/server.go
  ffs/scheduler/internal/trackstore/trackstore.go
  ffs/scheduler/internal/trackstore/trackstore_test.go
  index/miner/module/miner.go
  lotus/client.go
Labels: fix, patch

#662 minerselector/sr2: filter by maxprice and always query ask && FFS MinPieceSize condition
  api/server/server.go
  cmd/powd/main.go
  docker/Makefile
  ffs/filcold/filcold.go
  ffs/integrationtest/filters/filters_test.go
  ffs/integrationtest/general/general_test.go
  ffs/integrationtest/integrationtest.go
  ffs/minerselector/sr2/sr2.go
  go.mod
  go.sum
Labels: enhancement, patch

#668 SR2 miner selector price cap & index refactor
  cmd/powd/main.go
  ffs/minerselector/sr2/sr2.go
  ffs/minerselector/sr2/sr2_test.go
  ffs/scheduler/scheduler_storage.go
  go.sum
  index/miner/module/meta.go
  index/miner/module/miner.go
  index/miner/module/miner_test.go
  index/miner/module/onchain.go
Labels: enhancement, patch

#671 index/miners: make corrupted checkpoint a recoverable error & Lotus v0.10.1 update
  chainstore/chainstore.go
  docker/Makefile
  docker/docker-compose-localnet.yaml
  go.mod
  go.sum
  tests/ldevnet.go
  wallet/module/wallet.go
Labels: enhancement, minor

#674 Remove some methods that shold be admin
  api/client/net.go
  api/client/net_test.go
  api/client/wallet.go
  cli-docs/pow/pow_net.md
  cli-docs/pow/pow_net_connect.md
  cli-docs/pow/pow_net_disconnect.md
  cli-docs/pow/pow_wallet.md
  cli-docs/pow/pow_wallet_send.md
  cmd/pow/cmd/net_connect.go
  cmd/pow/cmd/net_disconnect.go
  cmd/pow/cmd/wallet_send.go
  net/rpc/rpc.go
  net/rpc/rpc.pb.go
  net/rpc/rpc.proto
  wallet/rpc/rpc.go
  wallet/rpc/rpc.pb.go
  wallet/rpc/rpc.proto
Labels: chore, patch

#675 increase deadlines for stage and get
  cmd/pow/cmd/ffs_get.go
  cmd/pow/cmd/ffs_stage.go
Labels: bugfix, patch

#677 Use configured deal timeout for storage deal monitoring
  api/server/server.go
  deals/module/deals.go
  deals/module/deals_test.go
  ffs/integrationtest/integrationtest.go
  ffs/manager/manager_test.go
Labels: bugfix, patch

#678 Fix ShowAll to ignore ErrNotFound
  cmd/pow/cmd/ffs_show.go
  ffs/rpc/rpc.go
Labels: bugfix, patch

#680 Fix empty array items in ShowAll response
  ffs/rpc/rpc.go
  ffs/types.go
Labels: bugfix, patch

#681 switch testnet to mainnet
  README.md
  docker/Makefile
  fchost/config.go
  fchost/fchost_test.go
Labels: chore, patch

#682 update go-ds-mongo and account for errors in queries
  deals/module/deals.go
  deals/module/store.go
  ffs/api/istore.go
  ffs/auth/auth.go
  ffs/joblogger/joblogger.go
  ffs/scheduler/internal/rjstore/rjstore.go
  ffs/scheduler/internal/sjstore/sjstore.go
  go.mod
  go.sum
  reputation/internal/source/store.go
  tests/txmapds.go
Labels: bugfix, patch

#684 Add flag to disable non compliant apis
  api/server/server.go
  cmd/powd/main.go
Labels: feature, patch

#687 update Lotus to v1.1.0 & fix minimum piece size in devnet
  .golangci.yml
  api/server/server.go
  docker/Makefile
  go.mod
  go.sum
Labels: bugfix, patch

#691 Fix canceling retry
  ffs/integrationtest/scheduler/scheduler_test.go
  ffs/scheduler/scheduler.go
Labels: bugfix, patch

#692 update mainnet bootstrap peers
  fchost/config.go
Labels: chore, patch

#694 Auto-throttling plus many improvements & fixes.
  api/client/asks.go
  api/client/utils_test.go
  api/server/server.go
  chainsync/chainsync.go
  chainsync/chainsync_test.go
  cmd/pow/cmd/asks_get.go
  cmd/pow/cmd/asks_query.go
  cmd/powd/main.go
  deals/module/deals.go
  deals/module/deals_test.go
  docker/Makefile
  ffs/filcold/filcold.go
  ffs/integrationtest/integrationtest.go
  ffs/interfaces.go
  ffs/minerselector/reptop/reptop.go
  ffs/minerselector/sr2/sr2.go
  ffs/minerselector/sr2/sr2_test.go
  filchain/filchain.go
  gateway/gateway.go
  go.mod
  go.sum
  index/ask/rpc/rpc.go
  index/ask/rpc/rpc.pb.go
  index/ask/rpc/rpc.proto
  index/ask/runner/runner.go
  index/ask/runner/runner_test.go
  index/ask/types.go
  index/faults/module/faults.go
  index/miner/module/meta.go
  index/miner/module/onchain.go
  lotus/client.go
  lotus/client_test.go
  lotus/metrics.go
  net/lotus/module.go
  paych/lotus/module.go
  tests/ldevnet.go
  wallet/module/wallet.go
Labels: enhancement, patch
