Repository textileio/powergate, pull requests merged in 2020-09, with the labels that each got.

#608 Enable release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore, patch

#609 Bump default autofund amount & fail fast if not enough balance for autofunding
  cmd/powd/main.go
  wallet/module/wallet.go
Labels: enhancement, patch

#613 Publish Docker image on release publish
  .github/workflows/docker.yml
Labels: bugfix, patch

#614 SR2 miner selector & safer default StorageConfig config
  api/client/utils_test.go
  api/server/server.go
  cmd/powd/main.go
  docker/Makefile
  docker/docker-compose-localnet.yaml
  ffs/filcold/filcold.go
  ffs/integrationtest/config/config_test.go
  ffs/integrationtest/unfreeze/unfreeze_test.go
  ffs/manager/manager.go
  ffs/minerselector/sr2/sr2.go
  ffs/scheduler/scheduler_storage.go
  go.mod
  go.sum
  index/miner/module/miner_test.go
  index/miner/module/onchain.go
  tests/ldevnet.go
Labels: feature, patch

#620 enable sr2 minerselector by default
  cmd/powd/main.go
Labels: enhancement, patch

#621 fix miner selector url
  cmd/powd/main.go
Labels: fix, patch

#622 recognize ignition network
  fchost/config.go
Labels: feature, patch

#623 remove peter's miners, rep factor 1
  api/server/server.go
  ffs/manager/manager.go
Labels: chore, patch

#625 force reputation minerselector in localnet
  api/server/server.go
Labels: fix, patch

#626 Fix release artifacts
  Makefile
Labels: chore, patch

#631 pow ffs sign and verify
  api/client/ffs.go
  cli-docs/pow/pow_ffs.md
  cli-docs/pow/pow_ffs_sign.md
  cli-docs/pow/pow_ffs_verify.md
  cmd/pow/cmd/ffs_sign.go
  ffs/api/api_wallet.go
  ffs/integrationtest/wallet/wallet_test.go
  ffs/interfaces.go
  ffs/rpc/rpc.go
  ffs/rpc/rpc.pb.go
  ffs/rpc/rpc.proto
  go.mod
  go.sum
  wallet/module/wallet.go
Labels: feature, patch
