Repository textileio/powergate, pull requests merged in 2020-12, with the labels that each got.

#720 Update to Lotus v1.2.2
  deals/module/deals_test.go
  docker/Makefile
  docker/docker-compose-localnet.yaml
  go.mod
  go.sum
  migration/migration1.go
  tests/ldevnet.go
Labels: chore, patch

#721 scheduler: add missing free-slot signal on resumed jobs
  ffs/scheduler/scheduler.go
Labels: bugfix, patch

#725 Cid info fix + sorting storage jobs
  api/server/user/data.go
  ffs/api/api.go
  ffs/api/istore.go
  ffs/scheduler/internal/sjstore/sjstore.go
Labels: bugfix, patch

#726 Data.Info(<cid>) get executing jobs for provided cid
  api/server/user/data.go
  api/server/user/service.go
  cmd/powd/main.go
Labels: bugfix, fix, patch

#731 Lotus v1.3.0 update
  docker/Makefile
  docker/docker-compose-localnet.yaml
  go.mod
  go.sum
  tests/ldevnet.go
Labels: chore, patch

#735 Update Lotus docker image to v1.4.0
  docker/Makefile
  go.mod
  go.sum
Labels: chore, patch

#734 Make embedded logging setup optional to support ipfs/go-log environment variables
  cmd/powd/main.go
Labels: feature, patch
