Repository textileio/powergate, pull requests merged in 2020-11, with the labels that each got.

#702 fix cancel arg constraint
  cmd/pow/cmd/storage_jobs_cancel.go
Labels: bugfix, patch

#705 Improve deal making efficiency & Lotus v1.1.3 update & fixes
  api/client/admin_test.go
  api/client/utils_test.go
  api/server/server.go
  chainsync/chainsync.go
  cmd/powd/main.go
  deals/module/deals.go
  deals/module/deals_test.go
  docker/Makefile
  docker/docker-compose-localnet.yaml
  ffs/filcold/filcold.go
  ffs/integrationtest/scheduler/scheduler_test.go
  ffs/interfaces.go
  ffs/scheduler/scheduler_storage.go
  ffs/types.go
  gateway/gateway.go
  go.mod
  go.sum
  index/miner/module/onchain.go
  index/miner/types.go
  reputation/internal/source/store.go
  reputation/reputation.go
  tests/ldevnet.go
  util/util.go
Labels: enhancement, minor

#709 gateway: fix epoch to date
  .github/workflows/review.yml
  Dockerfile
  cmd/powd/main.go
  gateway/gateway.go
Labels: fix, patch

#710 Support Calibration Network
  docker/Makefile
  fchost/config.go
Labels: enhancement, patch

#711 Lotus v1.2.0 update
  docker/Makefile
  docker/docker-compose-localnet.yaml
  go.mod
  go.sum
  tests/ldevnet.go
Labels: enhancement, patch

#713 Bump lotus docker image
  docker/Makefile
Labels: enhancement, patch

#714 Correct value for start epoch in API
  api/server/user/util.go
Labels: fix, patch
